export const TASK_TYPES = [
  { key: 'limited_sale', label: '限时发售', icon: '⏰', desc: '指定时间自动抢购' },
  { key: 'market_sniping', label: '市场抢单', icon: '🎯', desc: '监控市场低价自动抢单' },
  { key: 'synthesis', label: '活动合成', icon: '⚗️', desc: '按配方消耗材料合成' },
  { key: 'decomposition', label: '藏品分解', icon: '🔨', desc: '将藏品分解为材料' },
  { key: 'custom', label: '自定义任务', icon: '🔧', desc: '自定义点击/等待流程' },
];

export const PLATFORMS = [
  { key: 'yluc', label: '元初', homeUrl: 'https://m.yluc.com' },
  { key: 'jingtan', label: '鲸探', homeUrl: '' },
  { key: 'huanhe', label: '幻核', homeUrl: '' },
  { key: 'xmeta', label: 'X Meta', homeUrl: '' },
  { key: 'custom', label: '自定义平台', homeUrl: '' },
];

export const DEFAULT_SETTINGS = {
  randomDelayMin: 0.5,
  randomDelayMax: 2.0,
  headless: false,
  screenshotOnSuccess: true,
  soundNotify: true,
  popupNotify: true,
  autoRestart: true,
  browser: 'chromium',
  userDataDir: '',
  proxy: '',
  monitorRefreshMs: 2000,
  maxConcurrency: 3,
  // 微信推送
  wechatServerChan: false,
  serverChanKey: '',
  wechatWorkWebhook: false,
  workWebhookUrl: '',
  // PushPlus 推送
  pushplusEnabled: false,
  pushplusToken: '',
  pushplusTopic: '',
};

export const DEFAULT_PLATFORMS = [
  {
    id: 'plat-yluc-default',
    name: '元初 (Origin Yuan)',
    key: 'yluc',
    homeUrl: 'https://h5.yluc.cn/#/pages/index/index',
    loginUrl: 'https://h5.yluc.cn/#/pages/login/index',
    marketUrl: 'https://h5.yluc.cn/#/pages/market/index',
    warehouseUrl: 'https://h5.yluc.cn/#/pages/warehouse/index',
    activityUrl: 'https://h5.yluc.cn/#/pages/activity/index',
    saleUrl: 'https://h5.yluc.cn/#/pages/goods/index',
    noticeUrl: '',
    selectors: {
      loginPhone: '.login-form_input.phone .uni-input-input',
      loginPassword: '.uni-input-input[type="password"]',
      loginButton: '.animate__animated.animate__fadeIn:has-text("立即登录")',
      userAvatar: '.mine-avatar, .user-avatar, [class*="avatar"]',
      marketSearchInput: '',
      marketSearchButton: '',
      marketItemCard: '',
      marketItemName: '',
      marketItemPrice: '',
      marketItemId: '',
      marketTotalCount: '',
      marketLockedCount: '',
      marketMinPrice: '',
      marketMaxPrice: '',
      marketTypeTab: '',
      buyButton: '',
      confirmPrice: '',
      confirmButton: '',
      quantityInput: '',
      payPasswordInput: '',
      finalPayButton: '',
      activityItem: '',
      materialItem: '',
      materialName: '',
      materialQuantityInput: '',
      synthesisCountInput: '',
      synthesisButton: '',
      warehouseItem: '',
      warehouseItemName: '',
      warehouseItemCount: '',
      decomposeEntry: '',
      decomposeCountInput: '',
      decomposeConfirmButton: '',
      // 公告/活动通知相关选择器
      noticeItem: '.zp-paging-container-content > uni-view.item',
      noticeTitle: '.notice-title',
      noticeTime: '.notice-time',
      noticeLink: '',
      noticeSummary: '',
    },
  },
];
